services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: fastapi-project
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    command: sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  mysql_data:
